version: "3"
services:
   web:
     image: "${DOCKER_IMAGE}:latest"
     ports:
     - "8001-8002:80"
     deploy:
        replicas: 2
     depends_on:
     - mysql
   mysql:
     image: kalyani145/java-mvn-privaterepos:mysql:8.0
     volumes:
     - db_data:/var/lib/mysql
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}